name: Composite Action
description: Composite action to perform build and tests

inputs:
  pom-file-path:
    description: 'Path to the Maven POM file'
    required: true
    default: './pom.xml'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'

    - name: Build
      run: mvn -f ${{ inputs.pom-file-path }} clean compile

    - name: Test
      run: mvn -f ${{ inputs.pom-file-path }} test
