name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Run Composite Action
        uses: ./.github/actions/composite-action
        with:
          pom-file-path: './pom.xml'